#batch/v1 tells it to use the JOB API
apiVersion: batch/v1
# we are running a Job, not a Pod
kind: Job

# set the name of the job
metadata:
  name: copy-pvc-to-s3

spec:

  template:
    spec:
      # should we restart on failure
      restartPolicy: Never
      # what containers will we need
      containers:
        # the name of the container
        - name: rclone-container
          # the image: can be from any public facing registry
          image: rclone/rclone
          # the working dir when the container starts
          workingDir: /develop/results
          # should Kube pull it
          imagePullPolicy: IfNotPresent

          # environment
          env:
            - name: RCLONE_CONFIG_NAUTILUS_TYPE
              value: s3
            - name: RCLONE_CONFIG_NAUTILUS_ENDPOINT
              value: http://rook-ceph-rgw-centrals3.rook-central
            - name: RCLONE_CONFIG_NAUTILUS_PROVIDER
              value: Other #might need to change
            - name: RCLONE_CONFIG_NAUTILUS_ACCESS_KEY_ID
              value: JPKIHDAZY41Q5IPG1SPM
            - name: RCLONE_CONFIG_NAUTILUS_SECRET_ACCESS_KEY
              value: 2AZNOB1ivWEGKV1UYK6HDb5KuEJJ0s5dxDBxQPEE
          # the command to run when the container starts
          command:
            [
              "rclone",
              "copy",
              "--progress",
              "--copy-links",
              "--transfers=16",
              "/develop/results/analysis/all_analysis",
              "nautilus:bradleys-bucket/all_analysis",
            ]
          # define the resources for this container
          resources:
            # limits - the max given to the container
            limits:
              memory: 8Gi
              cpu: 16 #make sure this matches transfer number
            requests:
              memory: 8Gi
              cpu: 16
          # what volumes should we mount
          volumeMounts:
            - mountPath: /develop/results
              name: training-results
      # tell Kube where to find the volumes we want to use
      volumes:
        - name: training-results
          persistentVolumeClaim:
            claimName: training-results
