# this is being used as the preprocessed data monitor
# kubectl apply -f pp_dataset_mon.yaml
# kubectl exec -it monitor-pp-data -- /bin/bash

# The files mounted to develop/data/preprocessed_data are numbered 0000..1500.pkl. 
# They contain data that has been reduced from the raw data in the pvc meep-dataset-v2. 
# Each file is about 27 MB and should be separated into train/valid folders.

# The script used to do the preprocessing is located at 
# https://github.com/Kovaleski-Research-Lab/general_3x3/tree/andy_branch/preprocess_data.py.


apiVersion: v1
kind: Pod
metadata:
  name: monitor-pp-data
spec:
  containers:
    - name: monitor-pp-data
      image: docker.io/kovaleskilab/meep:v3_lightning
      stdin: True
      tty: True
      resources:
        limits:
          memory: 4Gi
          cpu: 2
        requests:
          memory: 4Gi
          cpu: 2
      volumeMounts:
        - name: preprocessed-data 
          mountPath: /develop/data/preprocessed_data
          readOnly: True 
  volumes:
    - name: preprocessed-data 
      persistentVolumeClaim:
        claimName: preprocessed-data 
        readOnly: True 

  restartPolicy: Never
